#!/bin/bash


echo "Works"

if [ -z "$ASK_API_URL" ]
then
	echo "Environment varible 'ASK_API_URL' is not set"
fi

if [ -z "$ASK_MODEL" ]
then
	echo "Environment varible 'ASK_MODEL' is not set"
fi


if [ -z "$ASK_API_KEY" ]
then
	echo "Environment varible 'ASK_API_KEY' is not set"
fi



response=$(curl $ASK_API_URL -s \
 -H "Content-Type: application/json" \
 -H "Authorization: Bearer $ASK_API_KEY" \
 -d '{
 "model": "'$ASK_MODEL'",
 	"messages": [
 		{
 		"role": "system",
 		"content": "You are a CLI tool. Output plain text only. No yapping. Keep the output concise."
 	},
 	{
 		"role": "user",
 		"content": "Explain the importance of fast language models"
 	}
 ]
 }'
)
#hello
echo $response | jq -r '.choices[0].message.content'
